steps:
- id: 'ui.pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME-ui:latest || exit 0'
  ]
- id: 'ui.build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-ui:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-ui:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME-ui:latest',
    '.',
    '--build-arg', 'NODE_ENV=production',
    '--build-arg', 'BABEL_ENV=production'
  ]
- id: 'ui.lint'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run',
    '-w',
    '/usr/local/src/varnish',
    'gcr.io/$PROJECT_ID/$REPO_NAME-ui:$COMMIT_SHA',
    'lint'
  ]
