version: '3'
services:
    demo:
        build: .
        volumes:
            - './layout:/usr/local/src/varnish/layout'
            - './theme:/usr/local/src/varnish/theme'
            - './utils:/usr/local/src/varnish/utils'
            - './components:/usr/local/src/varnish/components'
            - './@types:/usr/local/src/varnish/@types'
            - './dist:/usr/local/src/varnish/dist'
            - './package.json:/usr/local/src/varnish/package.json'
            - './yarn.lock:/usr/local/src/varnish/yarn.lock'
            - './.eslintignore:/usr/local/src/varnish/.eslintignore'
            - './.eslintrc.json:/usr/local/src/varnish/.eslintrc.json'
            - './demo/config:/usr/local/src/varnish/demo/config'
            - './demo/scripts:/usr/local/src/varnish/demo/scripts'
            - './demo/public:/usr/local/src/varnish/demo/public'
            - './demo/src:/usr/local/src/varnish/demo/src'
            - './demo/package.json:/usr/local/src/varnish/demo/package.json'
            - './demo/tsconfig.json:/usr/local/src/varnish/demo/tsconfig.json'
            - './demo/yarn.lock:/usr/local/src/varnish/demo/yarn.lock'
            - './postcss.config.js:/usr/local/src/varnish/postcss.config.js'
        ports:
            - '3000:3000'
    watch-ts:
        build: .
        volumes:
            - './layout:/usr/local/src/varnish/layout'
            - './theme:/usr/local/src/varnish/theme'
            - './utils:/usr/local/src/varnish/utils'
            - './components:/usr/local/src/varnish/components'
            - './@types:/usr/local/src/varnish/@types'
            - './dist:/usr/local/src/varnish/dist'
            - './package.json:/usr/local/src/varnish/package.json'
            - './yarn.lock:/usr/local/src/varnish/yarn.lock'
            - './.eslintignore:/usr/local/src/varnish/.eslintignore'
            - './.eslintrc.json:/usr/local/src/varnish/.eslintrc.json'
            - './postcss.config.js:/usr/local/src/varnish/postcss.config.js'
        working_dir: '/usr/local/src/varnish'
        command: [ 'watch:ts' ]
    watch-theme:
        build: .
        volumes:
            - './layout:/usr/local/src/varnish/layout'
            - './theme:/usr/local/src/varnish/theme'
            - './utils:/usr/local/src/varnish/utils'
            - './components:/usr/local/src/varnish/components'
            - './@types:/usr/local/src/varnish/@types'
            - './dist:/usr/local/src/varnish/dist'
            - './package.json:/usr/local/src/varnish/package.json'
            - './yarn.lock:/usr/local/src/varnish/yarn.lock'
            - './.eslintignore:/usr/local/src/varnish/.eslintignore'
            - './.eslintrc.json:/usr/local/src/varnish/.eslintrc.json'
            - './postcss.config.js:/usr/local/src/varnish/postcss.config.js'
        working_dir: '/usr/local/src/varnish'
        command: [ 'watch:theme' ]



