version: '3'
services:
  server:
    build: ./server
    volumes:
      - './server:/usr/local/src/skiff/app/server'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
  ui:
    build: ./ui
    volumes:
      - './ui/src:/usr/local/src/skiff/app/ui/src'
      - './ui/public:/usr/local/src/skiff/app/ui/public'
      - './ui/package.json:/usr/local/src/skiff/app/ui/package.json'
      - './ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json'
      - './ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
